language: java

sudo: false

jdk: openjdk15

addons:
  postgresql: "10"

services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE \"forum\";" -U postgres

branches:
  only:
    - master
    - development

notifications:
  email:
    recipients:
      - bujhtitxrf@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
